# Generated by Django 4.2.30 on 2026-07-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id_iva', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_iva', models.CharField(max_length=20, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'iva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaProducto',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'marca_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('contenido_neto', models.DecimalField(decimal_places=1, max_digits=10)),
                ('unidad_contenido', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecioInicialProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.OneToOneField(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='precio_inicial', to='producto.producto')),
            ],
            options={
                'db_table': 'precio_inicial_producto',
            },
        ),
    ]
